<?xml version="1.0"?>
<robot  xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:property name="arm_base_length" value="0.1"/>
    <xacro:property name="arm_base_width" value="0.1"/>
    <xacro:property name="arm_base_height" value="0.02"/>
    <xacro:property name="fore_arm_radius" value="0.02"/>
    <xacro:property name="fore_arm_length" value="0.3"/>
    <xacro:property name="hand_radius" value="0.02"/>
    <xacro:property name="hand_length" value="0.3"/>

    <link name="arm_base_link">

        <visual>
            <geometry>   
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}"/>
            </geometry>
            <origin xyz="0 0 ${arm_base_height/2}" rpy="0 0 0" />
            <material name="orange"/>
        </visual>
        <!-- <collision>
            <geometry>   
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="5.0" x="${base_length}" y="${base_width}" z="${base_height}"
                           o_xyz="0 0 ${base_height/2.0}" o_rpy="0 0 0 "/> -->
    </link>

    <link name="fore_arm_link">

        <visual>
            <geometry>   
                    <cylinder radius="${fore_arm_radius}" length="${fore_arm_length}" />
            </geometry>
            <origin xyz="0 0 ${fore_arm_length/2}" rpy="0 0 0" />
            <material name="yellow"/>
        </visual>
    </link>

    <link name="hand_link">

        <visual>
            <geometry>   
                    <cylinder radius="${hand_radius}" length="${hand_length}" />
            </geometry>
            <origin xyz="0 0 ${hand_length/2}" rpy="0 0 0" />
            <material name="orange"/>
        </visual>
    </link>

    <joint name="arm_base_fore_arm_joint" type="revolute">
        <parent link ="arm_base_link"/>
        <child link="fore_arm_link"/>
        <limit effort="100" velocity="100" lower="0" upper="${pi/2}" />
        <axis xyz="0 1 0" />
        <origin xyz="0 0 ${arm_base_height}" rpy="0 0 0"/>

    </joint>
    <joint name="fore_arm_hand_joint" type="revolute">
        <parent link ="fore_arm_link"/>
        <child link="hand_link"/>
        <limit effort="100" velocity="100" lower="0" upper="${pi/2}" />
        <axis xyz="0 1 0" />
        <origin xyz="0 0 ${fore_arm_length}" rpy="0 0 0"/>

    </joint>
</robot>