<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
    
    <xacro:property name="base_length" value="0.6"/>
    <xacro:property name="base_width" value="0.4"/>
    <xacro:property name="base_height" value="0.2"/>
    <xacro:property name="wheel_raidus" value="0.1"/>
    <xacro:property name="wheel_length" value="0.05"/>
    <link name="base_footprint_link"/>
        

    <link name="base_link">
        <visual>
            <geometry>   
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0" />
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>   
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="5.0" x="${base_length}" y="${base_width}" z="${base_height}"
                           o_xyz="0 0 ${base_height/2.0}" o_rpy="0 0 0 "/>
    </link>


    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_raidus}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2.0} 0 0" />
                <material name="grey"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${wheel_raidus}"  />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
            </collision>
            <xacro:cylinder_inertia m="1.0" r="${wheel_raidus}" l="${wheel_length}"
                           o_xyz="0 0 0" o_rpy="${pi/2.0} 0 0 "/>
        </link>
    </xacro:macro>
    <xacro:wheel_link prefix="right"/>
    <xacro:wheel_link prefix="left"/>
    <!-- <link name="right_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_raidus}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi/2.0} 0 0" />
            <material name="grey"/>
        </visual>
    </link>
    <link name="left_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_raidus}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi/2.0} 0 0" />
            <material name="grey"/>
        </visual>
    </link> -->

    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${wheel_raidus/2}"  />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="grey"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_raidus/2}"  />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:sphere_inertia m="0.5" r="${wheel_raidus/2}" 
                           o_xyz="0 0 0" o_rpy="0 0 0 "/>
    </link>

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link ="base_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="${-base_length/4.0} ${-(base_width+wheel_length)/2} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link ="base_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="${-base_length/4.0} ${(base_width+wheel_length)/2} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link ="base_link"/>
        <child link="caster_wheel_link"/>
        <origin xyz="${base_length/3.0} 0 ${-wheel_raidus/2}" rpy="0 0 0"/>

    </joint>

    <joint name="base_base_footprint_joint" type="fixed">
        <parent link ="base_footprint_link"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${wheel_raidus}" rpy="0 0 0"/>

    </joint>
    <joint name="arm_base_base_joint" type="fixed">
        <parent link ="base_link"/>
        <child link="arm_base_link"/>
        <origin xyz="${(base_length-arm_base_length)/2} 0 ${base_height}" rpy="0 0 0"/>

    </joint>

    <!-- <link name="second_link">
        <visual>
            <geometry>
                <cylinder radius="0.1" length="0.2" />
            </geometry>
            <origin xyz="0 0 0.1" rpy="0 0 0" />
            <material name="grey"/>
        </visual>
    </link> -->

    <!-- <link name="third_link">
        <visual>
            <geometry>
                <box size="0.1 0.1 0.1"/>
            </geometry>
            <origin xyz="0 0 0.05" rpy="0 0 0" />
            <material name="green"/>
        </visual>
    </link> -->

    <!-- <joint name="base_second_joint" type="prismatic">
        <parent link ="base_link"/>
        <child link="second_link"/>
        <origin xyz="0 0 0.2" rpy="0 0 0"/>
        <axis xyz="1 0 0"/>
        <limit lower="-1.57" upper="1.57" velocity="100" effort="100" />
    </joint> -->
<!-- 
    <joint name="second_third_joint" type="fixed">
        <parent link ="second_link"/>
        <child link="third_link"/>
        <origin xyz="0 0 0.2" rpy="0 0 0"/>
    </joint> -->
</robot>